# Generated by Django 2.1.7 on 2020-05-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20190507_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FilePathField(path='C:\\Users\\sadox\\Desktop\\gs\\media'),
        ),
    ]
