# Generated by Django 2.2 on 2020-08-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20200530_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FilePathField(path='C:\\Users\\sadox\\Desktop\\gsgit\\gs\\media'),
        ),
    ]
